<?php

namespace Database\Seeders;

use App\Models\Resident;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ResidentSeeder extends Seeder
{
    public function run(): void
    {
        $residents = [
            // Penghuni tetap (permanent) — 15 orang untuk 15 rumah permanent
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Budi Santoso',
                'phone_number'        => '081234567801',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => 'Ketua RT sebelumnya',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Siti Rahayu',
                'phone_number'        => '081234567802',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Ahmad Fauzi',
                'phone_number'        => '081234567803',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Dewi Kusuma',
                'phone_number'        => '081234567804',
                'resident_type'       => 'permanent',
                'is_married'          => false,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => 'Tinggal sendiri',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Hendra Gunawan',
                'phone_number'        => '081234567805',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Rina Marlina',
                'phone_number'        => '081234567806',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Dodi Pratama',
                'phone_number'        => '081234567807',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Yuni Astuti',
                'phone_number'        => '081234567808',
                'resident_type'       => 'permanent',
                'is_married'          => false,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => 'WFH, sering di rumah',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Bambang Irawan',
                'phone_number'        => '081234567809',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Lestari Putri',
                'phone_number'        => '081234567810',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Wahyu Nugroho',
                'phone_number'        => '081234567811',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Endang Suryani',
                'phone_number'        => '081234567812',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Rizal Hakim',
                'phone_number'        => '081234567813',
                'resident_type'       => 'permanent',
                'is_married'          => false,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => 'Mahasiswa S2',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Mulyani Soetopo',
                'phone_number'        => '081234567814',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Agus Setiawan',
                'phone_number'        => '081234567815',
                'resident_type'       => 'permanent',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => null,
                'contract_end_date'   => null,
                'notes'               => null,
            ],

            // Penghuni kontrak (contract) — 3 orang untuk 3 dari 5 rumah temporary
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Kevin Hartono',
                'phone_number'        => '081234567816',
                'resident_type'       => 'contract',
                'is_married'          => false,
                'is_active'           => true,
                'contract_start_date' => '2026-01-01',
                'contract_end_date'   => '2026-12-31',
                'notes'               => 'Karyawan swasta, kontrak 1 tahun',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Fitri Handayani',
                'phone_number'        => '081234567817',
                'resident_type'       => 'contract',
                'is_married'          => true,
                'is_active'           => true,
                'contract_start_date' => '2026-03-01',
                'contract_end_date'   => '2026-02-28',
                'notes'               => 'Pindah dari luar kota',
            ],
            [
                'id'                  => Str::uuid(),
                'full_name'           => 'Rendi Kurniawan',
                'phone_number'        => '081234567818',
                'resident_type'       => 'contract',
                'is_married'          => false,
                'is_active'           => true,
                'contract_start_date' => '2026-06-01',
                'contract_end_date'   => '2026-11-30',
                'notes'               => 'Kontrak 6 bulan',
            ],
        ];

        foreach ($residents as $data) {
            Resident::create(array_merge($data, [
                'id_card_photo' => null,
                'created_at'    => now(),
                'updated_at'    => now(),
            ]));
        }
    }
}
